# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='vowel',
            field=models.BooleanField(default=False),
        ),
    ]
