# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writecode', '0002_descriptor_vowel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Coder',
        ),
        migrations.DeleteModel(
            name='Descriptor',
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
